name: AutoSmeltOre
api: 4.0.0
version: 0.0.3
main: YTBJero\AutoSmeltOre\Main
author: DavidGlitch04

permissions:
    autosmeltore.action.allow:
        default: op
        description: "Allow player to use AutoSmeltOre"
